"""Русские подписи полей, зеркало static/js/schema.js.

Печатный отчёт не может показать подсказку по наведению: подпись поля - всё,
что видит читатель на бумаге. Тест test_field_labels_match_javascript следит,
чтобы список не разъезжался с формой ввода.
"""
from __future__ import annotations


SCHEMA_FIELD_LABELS: dict[str, str] = {
    "Patient_ID": "ID случая",
    "Full_name": "ФИО пациента",
    "Sex": "Пол",
    "Age": "Возраст, лет",
    "Height_cm": "Рост, см",
    "Weight_kg": "Масса, кг",
    "BMI": "BMI",
    "Main_complaint": "Основная жалоба",
    "Complaint_duration": "Длительность жалоб",
    "Onset_context": "Контекст начала симптомов",
    "Smoking_status": "Курение",
    "Hypertension": "Артериальная гипертензия",
    "Diabetes_mellitus": "Сахарный диабет",
    "Dyslipidemia": "Дислипидемия",
    "Obesity_or_Metabolic_syndrome": "Ожирение / метаболический синдром",
    "Chronic_kidney_disease_stage": "ХБП, стадия",
    "Family_history_early_CVD": "Семейный анамнез раннего ССЗ",
    "Physical_activity_level": "Физическая активность",
    "Alcohol_and_other_substances": "Алкоголь и другие вещества",
    "Prior_MI": "Перенесённый инфаркт миокарда",
    "Prior_stroke_TIA": "Инсульт / ТИА в анамнезе",
    "Prior_PE_DVT": "ТЭЛА / ТГВ в анамнезе",
    "Prior_cardiac_surgeries": "Кардиохирургические операции",
    "Prior_congenital_heart_defect_and_surgeries": "ВПС и операции",
    "History_myocarditis_pericarditis": "Миокардиты / перикардиты",
    "Other_major_diseases": "Другие важные заболевания",
    "Known_IHD": "Известная ИБС",
    "Known_HF": "Хроническая сердечная недостаточность",
    "Known_arrhythmias": "Аритмии",
    "Known_valvular_disease": "Клапанные пороки",
    "Known_aortic_or_peripheral_arterial_disease": "Аорта / периферические артерии",
    "Known_pulmonary_hypertension": "Лёгочная гипертензия",
    "Known_congenital_heart_disease": "Врожденные пороки сердца",
    "Blood_pressure_right_systolic_mmHg": "АД справа, сист.",
    "Blood_pressure_right_diastolic_mmHg": "АД справа, диаст.",
    "Blood_pressure_left_systolic_mmHg": "АД слева, сист.",
    "Blood_pressure_left_diastolic_mmHg": "АД слева, диаст.",
    "Heart_rate_bpm": "ЧСС",
    "Resp_rate": "ЧДД",
    "SpO2_room_air_percent": "SpO2, %",
    "Peripheral_edema": "Периферические отёки",
    "Lung_auscultation": "Аускультация лёгких",
    "Heart_auscultation": "Аускультация сердца",
    "Peripheral_pulses": "Периферические пульсы",
    "Hb_g_L": "Hb, г/л",
    "WBC_10e9_L": "WBC, 10^9/л",
    "PLT_10e9_L": "PLT, 10^9/л",
    "Creatinine_umol_L": "Креатинин, мкмоль/л",
    "eGFR_ml_min_1_73m2": "СКФ, мл/мин/1.73 м2",
    "ALT_U_L": "АЛТ, Ед/л",
    "AST_U_L": "АСТ, Ед/л",
    "Na_mmol_L": "Na, ммоль/л",
    "K_mmol_L": "K, ммоль/л",
    "Mg_mmol_L": "Mg, ммоль/л",
    "Glucose_fasting_mmol_L": "Глюкоза натощак",
    "HbA1c_percent": "HbA1c, %",
    "Total_cholesterol_mmol_L": "Общий холестерин",
    "LDL_mmol_L": "ЛПНП",
    "HDL_mmol_L": "ЛПВП",
    "Triglycerides_mmol_L": "Триглицериды",
    "Troponin_ng_L": "Тропонин, нг/л",
    "CKMB_U_L": "КФК-МВ, Ед/л",
    "NT_proBNP_pg_ml": "NT-proBNP, пг/мл",
    "INR": "INR",
    "APTT_sec": "APTT, сек",
    "Resting_ECG_summary": "ЭКГ покоя, сводка",
    "Holter_ECG_summary": "Холтер-ЭКГ, сводка",
    "ABPM_summary": "СМАД, сводка",
    "LVEDD_mm": "КДР ЛЖ, мм",
    "LVESD_mm": "КСР ЛЖ, мм",
    "LVEF_percent": "ФВ ЛЖ, %",
    "LA_diameter_mm": "ЛП, мм",
    "RV_diameter_mm": "ПЖ, мм",
    "PASP_mmHg": "PASP, мм рт.ст.",
    "IVS_thickness_mm": "МЖП, мм",
    "PW_LV_thickness_mm": "Задняя стенка ЛЖ, мм",
    "Mitral_valve_area_cm2": "Площадь МК, см2",
    "Aortic_valve_area_cm2": "Площадь АК, см2",
    "Valvular_regurgitation": "Клапанные регургитации",
    "Pericardial_effusion": "Перикардиальный выпот",
    "Exercise_test_summary": "Нагрузочный тест",
    "METs_max": "Макс. METs",
    "SixMWT_distance_m": "6-минутный тест, м",
    "Coronary_angiography_or_CTCA": "Коронарография / КТКА",
    "Aorta_CT_MR": "КТ/МРТ аорты",
    "Carotid_ultrasound": "УЗИ сонных артерий",
    "Peripheral_artery_imaging": "Периферические артерии",
    "Venous_ultrasound": "УЗИ вен",
    "Coronary_stents": "Стенты коронарных артерий",
    "CABG_details": "АКШ, детали",
    "Valve_surgery_or_prosthesis": "Клапанные протезы/пластика",
    "Pacemaker_ICD_CRT": "ЭКС / ICD / CRT",
    "Other_advanced_therapies": "Другие терапии",
    "Antiplatelets": "Антиагреганты",
    "Anticoagulants": "Антикоагулянты",
    "Beta_blockers": "Бета-блокаторы",
    "ACEi_ARB_ARNI": "иАПФ / БРА / ARNI",
    "MRA": "MRA",
    "SGLT2_inhibitors": "SGLT2-ингибиторы",
    "Diuretics": "Диуретики",
    "Antiarrhythmics": "Антиаритмики",
    "Lipid_lowering": "Липидснижающая терапия",
    "Antidiabetic_drugs": "Гипогликемические препараты",
    "Other_relevant_drugs": "Другое",
    "NYHA_class": "NYHA класс",
    "Angina_CCS_class": "Класс стенокардии CCS",
    "Killip_class_if_acute_MI": "Killip при ОИМ",
    "CHA2DS2_VASc": "CHA2DS2-VASc",
    "HAS_BLED": "HAS-BLED",
    "Main_cardiovascular_diagnosis_text": "Основной СС-диагноз",
    "Other_cardiovascular_diagnoses": "Другие СС-диагнозы",
    "Non_cardiac_comorbidities": "Несердечные коморбидности",
    "ICD10_codes": "Коды МКБ-10, через ;",
    "Final_model_diagnosis": "Диагноз модели",
    "Model_ICD10_codes": "Коды МКБ-10 модели",
    "Model_treatment_recommendations": "Рекомендации по лечению",
    "Model_rehabilitation_recommendations": "Реабилитация и образ жизни",
}
